language: c
compiler:
  - gcc
  - clang
before_install:
  - if [ "$CC" == "clang" ] ; then export CXX=clang++ ; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq lcov
  - gem install coveralls-lcov
  - sh ./utilities/download_gtest.sh
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DOQS_ENABLE_COVERAGE=ON -DOQS_BUILD_TESTS=ON -DOQS_RUN_EXAMPLES_AS_TESTS=ON ..
  - make -j4
  - ctest --output-on-failure
  - rm -rf *
  - cmake -DCMAKE_BUILD_TYPE=Debug -DOQS_ENABLE_COVERAGE=ON -DOQS_BUILD_TESTS=ON -DOQS_RUN_EXAMPLES_AS_TESTS=ON -DBUILD_SHARED_LIBS=ON ..
  - make -j4 
  - ctest --output-on-failure
after_success:
  - lcov -d tests -d src -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'gtest*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
